### ISSUE TITLE
package.json main needs updating, resulting from lib to src rename

### ISSUE THREAD

**Issue by eephillip** [troygoode/node-roll#13]
https://github.com/troygoode/node-roll/blob/f5c0d003f1505a2a329172d28bab05a1cf8e3a47/package.json#L30

**Comment by clevett** [comment]
Also ran into this issue trying to deploy.

**Comment by eephillip** [comment]
#14 fixes

**Comment by troygoode** [comment]
merged #14 and published fix with `1.3.1` – sorry about that!
