### ISSUE TITLE
Calling .rolled does not result in expected output.

### ISSUE THREAD

**Issue by Anaerin** [troygoode/node-roll#7]
According to the documentation:
    var yahtzee = roll.roll('5d6');
    console.log(yahtzee.rolled); //yahtzee.rolled will return something like [5, 2, 4, 6, 1] rather than the sum

But doing something like:
    var myRoll = roll.roll("2d10+5");
    console.log(myRoll.rolled); // returns "6"

It returns the sum of the rolled die, not the individual die. I'm presuming that this is because the adding the modifier overwrites the list of rolled die.

**Comment by troygoode** [comment]
@Anaerin this was fixed a couple of years ago but didn't make it into the published npm version... whoops

I just published a new version, `1.2.0`, that works as you'd expect. It even has a test just for your issue:

https://github.com/troygoode/node-roll/blob/master/test/test.js#L55
